### ISSUE TITLE
NameError: name 'hid' is not defined

### ISSUE THREAD

**Issue by torkelrogstad** [bitcoin-core/HWI#143]
```
$ poetry install 
Installing dependencies from lock file

Nothing to install or update

  - Installing hwi (1.0.0)
A setup.py file already exists. Using it.

$ ./hwi.py enumerate
Traceback (most recent call last):
  File "./hwi.py", line 7, in <module>
    main()
  File "/home/torkel/dev/python/bitcoin-core-hwi/hwilib/cli.py", line 222, in main
    result = process_commands(sys.argv[1:])
  File "/home/torkel/dev/python/bitcoin-core-hwi/hwilib/cli.py", line 178, in process_commands
    return args.func(args)
  File "/home/torkel/dev/python/bitcoin-core-hwi/hwilib/cli.py", line 30, in enumerate_handler
    return enumerate(password=args.password)
  File "/home/torkel/dev/python/bitcoin-core-hwi/hwilib/commands.py", line 37, in enumerate
    result.extend(imported_dev.enumerate(password))
  File "/home/torkel/dev/python/bitcoin-core-hwi/hwilib/devices/ledger.py", line 338, in enumerate
    for d in hid.enumerate(LEDGER_VENDOR_ID, LEDGER_DEVICE_ID):
NameError: name 'hid' is not defined
```

Adding `import hid` at the top of `hwilib/devices/ledger.py` fixes the issue.

**Comment by lontivero** [comment]
I've got the same error message after:

```
$ sudo apt install libusb-1.0-0-dev libudev-dev
$ git clone https://github.com/bitcoin-core/HWI.git
$ cd HWI
$ ./hwi.py enumerate
```

Adding import hid at the top of hwilib/devices/ledger.py fixes the issue as @torkelrogstad says.

**Comment by achow101** [comment]
Does this error occur if you use the released binaries?

***

I'm wondering what I've done differently in my setup that makes me unable to reproduce this.

**Comment by lontivero** [comment]
The binary release works okay.
