### ISSUE TITLE
hwi 1.0.1 release does not work on Windows 10

### ISSUE THREAD

**Issue by nopara73** [bitcoin-core/HWI#208]
1. Download and unzip the release.
2. run `hwi enumerate` or anything else.

```
hwi enumerate
Traceback (most recent call last):
  File "hwi.py", line 5, in <module>
  File "C:\users\root\Local Settings\Application Data\pypoetry\Cache\virtualenvs\hwi-py3.6\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "hwilib\cli.py", line 3, in <module>
  File "C:\users\root\Local Settings\Application Data\pypoetry\Cache\virtualenvs\hwi-py3.6\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "hwilib\commands.py", line 12, in <module>
  File "C:\users\root\Local Settings\Application Data\pypoetry\Cache\virtualenvs\hwi-py3.6\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "hwilib\udevinstaller.py", line 5, in <module>
ImportError: cannot import name 'geteuid'
[9748] Failed to execute script hwi
```

**Comment by lontivero** [comment]
Confirmed. I downloaded the release from [here](https://github.com/bitcoin-core/HWI/releases/download/1.0.1/hwi-1.0.1-windows-amd64.zip) and it doesn't work on my Windows 10 VM.
