### ISSUE TITLE
Trezor simulator multisig sign crash 

### ISSUE THREAD

**Issue by Sjors** [bitcoin-core/HWI#301]
I created a 2 of 3 native segwit multisig wallet. I then created a PSBT (with a Bitcoin Core native descriptor wallet). When trying to sign the transaction, it:
1. shows the correct amount and destination
2. click OK
3. HWI returns with `{"error": "[Errno 61] Connection refused", "code": -13}`
4. meanwhile shows change address, but doesn't recoginize it (as expected, see #279)
5. "Signing transaction" seems to take forever, and can be interrupted by any HWI command

I thought this was implemented in #89. In fact there's actually a 2 of 3 multisig native segwit test: https://github.com/bitcoin-core/HWI/blob/master/test/test_device.py#L372 

I'm using the latest master of the Trezor T firmware, on macOS Catalina.

**Comment by achow101** [comment]
Any info from `--debug`?

**Comment by Sjors** [comment]
```
INFO:hwilib.devices.trezorlib.transport:Enumerating UdpTransport: found 1 devices
INFO:hwilib.devices.trezorlib.transport:Enumerating HidTransport: found 0 devices
INFO:hwilib.devices.trezorlib.transport:Enumerating WebUsbTransport: found 0 devices
DEBUG:root:Simulator found, using DebugLink
INFO:hwilib.devices.trezorlib.transport:looking for device by full path: udp:127.0.0.1:21324
INFO:hwilib.devices.trezorlib.client:creating client instance for device: udp:127.0.0.1:21324
DEBUG:hwilib.devices.trezorlib.transport.protocol:sending message: GetFeatures
DEBUG:hwilib.devices.trezorlib.transport.protocol:received message: Features
DEBUG:hwilib.devices.trezorlib.transport.protocol:sending message: GetFeatures
DEBUG:hwilib.devices.trezorlib.transport.protocol:received message: Features
DEBUG:hwilib.devices.trezorlib.transport.protocol:sending message: GetPublicKey
DEBUG:hwilib.devices.trezorlib.transport.protocol:received message: PublicKey
INFO:hwilib.devices.trezorlib.transport:Enumerating UdpTransport: found 1 devices
INFO:hwilib.devices.trezorlib.transport:Enumerating HidTransport: found 0 devices
INFO:hwilib.devices.trezorlib.transport:Enumerating WebUsbTransport: found 0 devices
DEBUG:root:Simulator found, using DebugLink
INFO:hwilib.devices.trezorlib.transport:looking for device by full path: udp:127.0.0.1:21324
INFO:hwilib.devices.trezorlib.client:creating client instance for device: udp:127.0.0.1:21324
DEBUG:hwilib.devices.trezorlib.transport.protocol:sending message: GetFeatures
DEBUG:hwilib.devices.trezorlib.transport.protocol:received message: Features
DEBUG:root:Simulator found, using DebugLink
INFO:hwilib.devices.trezorlib.transport:looking for device by full path: udp:127.0.0.1:21324
INFO:hwilib.devices.trezorlib.client:creating client instance for device: udp:127.0.0.1:21324
DEBUG:hwilib.devices.trezorlib.transport.protocol:sending message: GetFeatures
DEBUG:hwilib.devices.trezorlib.transport.protocol:received message: Features
DEBUG:hwilib.devices.trezorlib.transport.protocol:sending message: GetPublicKey
DEBUG:hwilib.devices.trezorlib.transport.protocol:received message: PublicKey
DEBUG:hwilib.devices.trezorlib.transport.protocol:sending message: SignTx
DEBUG:hwilib.devices.trezorlib.transport.protocol:received message: TxRequest
DEBUG:hwilib.devices.trezorlib.transport.protocol:sending message: TxAck
DEBUG:hwilib.devices.trezorlib.transport.protocol:received message: TxRequest
DEBUG:hwilib.devices.trezorlib.transport.protocol:sending message: TxAck
DEBUG:hwilib.devices.trezorlib.transport.protocol:received message: ButtonRequest
DEBUG:hwilib.devices.trezorlib.transport.protocol:sending message: ButtonAck
DEBUG:hwilib.devices.trezorlib.transport.protocol:sending message: DebugLinkDecision
```

Once I confirm the destination address:

```
DEBUG:hwilib.devices.trezorlib.transport.protocol:received message: TxRequest
DEBUG:hwilib.devices.trezorlib.transport.protocol:sending message: TxAck
DEBUG:hwilib.devices.trezorlib.transport.protocol:received message: ButtonRequest
DEBUG:hwilib.devices.trezorlib.transport.protocol:sending message: ButtonAck
DEBUG:hwilib.devices.trezorlib.transport.protocol:sending message: DebugLinkDecision
Traceback (most recent call last):
  File "/Users/sjors/dev/HWI/hwilib/errors.py", line 104, in handle_errors
    yield
  File "/Users/sjors/dev/HWI/hwilib/cli.py", line 246, in process_commands
    result = args.func(args, client)
  File "/Users/sjors/dev/HWI/hwilib/cli.py", line 57, in signtx_handler
    return signtx(client, psbt=args.psbt)
  File "/Users/sjors/dev/HWI/hwilib/commands.py", line 78, in signtx
    return client.sign_tx(tx)
  File "/Users/sjors/dev/HWI/hwilib/devices/trezor.py", line 61, in func
    return f(*args, **kwargs)
  File "/Users/sjors/dev/HWI/hwilib/devices/trezor.py", line 320, in sign_tx
    signed_tx = btc.sign_tx(self.client, "Testnet", inputs, outputs, tx_details, prevtxs)
  File "/Users/sjors/dev/HWI/hwilib/devices/trezorlib/tools.py", line 227, in wrapped_f
    return f(client, *args, **kwargs)
  File "/Users/sjors/dev/HWI/hwilib/devices/trezorlib/btc.py", line 155, in sign_tx
    res = client.call(messages.TxAck(tx=msg))
  File "/Users/sjors/dev/HWI/hwilib/devices/trezorlib/tools.py", line 227, in wrapped_f
    return f(client, *args, **kwargs)
  File "/Users/sjors/dev/HWI/hwilib/devices/trezorlib/client.py", line 171, in call
    resp = self._callback_button(resp)
  File "/Users/sjors/dev/HWI/hwilib/devices/trezorlib/client.py", line 158, in _callback_button
    self.ui.button_request(msg.code)
  File "/Users/sjors/dev/HWI/hwilib/devices/trezorlib/debuglink.py", line 166, in button_request
    self.debuglink.press_yes()
  File "/Users/sjors/dev/HWI/hwilib/devices/trezorlib/debuglink.py", line 108, in press_yes
    self.input(button=True)
  File "/Users/sjors/dev/HWI/hwilib/devices/trezorlib/debuglink.py", line 102, in input
    self._call(decision, nowait=True)
  File "/Users/sjors/dev/HWI/hwilib/devices/trezorlib/debuglink.py", line 40, in _call
    self.transport.write(msg)
  File "/Users/sjors/dev/HWI/hwilib/devices/trezorlib/transport/protocol.py", line 117, in write
    self.protocol.write(message)
  File "/Users/sjors/dev/HWI/hwilib/devices/trezorlib/transport/protocol.py", line 151, in write
    self.handle.write_chunk(chunk)
  File "/Users/sjors/dev/HWI/hwilib/devices/trezorlib/transport/udp.py", line 110, in write_chunk
    self.socket.sendall(chunk)
ConnectionRefusedError: [Errno 61] Connection refused
{"error": "[Errno 61] Connection refused", "code": -13}
```

**Comment by Sjors** [comment]
One of the other signers is a ColdCard simulator, which did sign successfully.

**Comment by achow101** [comment]
Does this only happen with multisig?

Do the tests pass?

**Comment by Sjors** [comment]
I just tried updating `work/bitcoin` and `work/trezor-firmware` to their latest master. I built the emulator: `BITCOIN_ONLY=1 pipenv run make build_unix`. I then ran then tests with `./run_tests.py --trezor-t`. Some of the tests fail, though it could be a local (macOS) environment issue, e.g. 

```
======================================================================
ERROR: trezor_t: test_type_only_autodetect (test_device.TestDeviceConnect)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sjors/dev/HWI/test/test_device.py", line 118, in setUp
    self.emulator.start()
  File "/Users/sjors/dev/HWI/test/test_trezor.py", line 60, in start
    client = TrezorClientDebugLink(wirelink)
UnboundLocalError: local variable 'wirelink' referenced before assignment
```

**Comment by achow101** [comment]
Is this still an issue?

**Comment by prusnak** [comment]
@Sjors ping?

**Comment by Sjors** [comment]
I haven't tried this recently. Feel free to close; I'll reopen if I run into it again.
