### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by calkob** [bitcoin-core/HWI#325]
Aftering connecting HW and running ./hwi.py enumerate  
i get the error below, tried it with a trezor and ledger, same error both time.  

Traceback (most recent call last):
  File "./hwi.py", line 6, in <module>
    from hwilib.cli import main
  File "/home/calkob/HWI/hwilib/cli.py", line 3, in <module>
    from .commands import backup_device, displayaddress, enumerate, find_device, \
  File "/home/calkob/HWI/hwilib/commands.py", line 8, in <module>
    from .serializations import PSBT
  File "/home/calkob/HWI/hwilib/serializations.py", line 21, in <module>
    from . import base58
  File "/home/calkob/HWI/hwilib/base58.py", line 15
    b58_digits: str = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz'
              ^
SyntaxError: invalid syntax

**Comment by nopara73** [comment]
Does the [released version](https://github.com/bitcoin-core/hwi/releases) work properly?

**Comment by calkob** [comment]
Released version is working, i might have been using an older version from Achow repo.  Thanks for the help as always.
