### ISSUE TITLE
Trezor model t wasabi help

### ISSUE THREAD

**Issue by gsud247** [bitcoin-core/HWI#339]
Im trying to load my trezor model t w/ passphrase w wasabi but wasabi keeps searching for hardware and then cancelling the task..

The trezor does prompt me to enter passphrase but nothing happens when i do.

**Comment by gsud247** [comment]
See

https://github.com/zkSNACKs/WalletWasabi/issues/3716

Thanks

**Comment by achow101** [comment]
Just to be sure, you are using Trezor 2.3.0 bitcoin only and forcing passphrase on device?

**Comment by achow101** [comment]
I'm unable to replicate this. It looks like you're using macOS, so I will look into this again next week when my mac arrives.

**Comment by gsud247** [comment]
2.3.1

Bitcoin only

Force pass on device

**Comment by gsud247** [comment]
Yes mac os

**Comment by nopara73** [comment]
Thank you @achow101!

**Comment by molnard** [comment]
@gsud247 v2.3.1 won't work with Wasabi. With v2.3.1 Trezor introduced a major compatibility issue: https://github.com/bitcoin-core/HWI/issues/338
https://blog.trezor.io/details-of-firmware-updates-for-trezor-one-version-1-9-1-and-trezor-model-t-version-2-3-1-1eba8f60f2dd

Your issue is related to v2.3.0 so downgrade to that version if you want to use Wasabi with Trezor.

**Comment by gsud247** [comment]
Ok.  I will downgrade and try once more.  Thanks.

**Comment by gsud247** [comment]
i have downgraded to 2.3.0

walletWasabi.Gui hwi donet run

i tried to connect twice and got this again after enetering a passphrase onto the device:

Please confirm action on your Trezor device
2020-06-08 13:33:19 WARNING	Program (93)	System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (The peer has been disconnected)
 ---> System.OperationCanceledException: The peer has been disconnected
   --- End of inner exception stack trace ---
2020-06-08 13:34:46 ERROR	ConnectHardwareWalletViewModel (140)	System.Threading.Tasks.TaskCanceledException: A task was canceled.
Please confirm action on your Trezor device
2020-06-08 13:38:19 ERROR	ConnectHardwareWalletViewModel (140)	System.Threading.Tasks.TaskCanceledException: A task was canceled.

**Comment by gsud247** [comment]
GGGGGs-iMac:~ ghh$ cd WalletWasabi/WalletWasabi/Microservices/Binaries/osx64
GGGGGs-iMac:osx64 ghh$ ./hwi enumerate
Please confirm action on your Trezor device

Again, after entering the passphrase on device...... nothing

**Comment by achow101** [comment]
Can you try `./hwi --debug enumerate`?

**Comment by gsud247** [comment]
i just used an old windows pc

and the model t and usb wire are working perfectly.. i am able to load the wallet

the issue seems isolated to my mac

ok @achow101 will try now

**Comment by gsud247** [comment]
GGGGs-iMac:osx64 ghh$ ./hwi --debug enumerate
INFO:hwilib.devices.trezorlib.transport:Enumerating WebUsbTransport: found 1 devices
INFO:hwilib.devices.trezorlib.transport:Enumerating UdpTransport: found 0 devices
INFO:hwilib.devices.trezorlib.transport:Enumerating HidTransport: found 0 devices
INFO:hwilib.devices.trezorlib.transport:looking for device by full path: webusb:020:2
INFO:hwilib.devices.trezorlib.client:creating client instance for device: webusb:020:2
DEBUG:hwilib.devices.trezorlib.transport.protocol:sending message: GetFeatures
DEBUG:hwilib.devices.trezorlib.transport.protocol:received message: Features
DEBUG:hwilib.devices.trezorlib.transport.protocol:sending message: GetPublicKey
DEBUG:hwilib.devices.trezorlib.transport.protocol:received message: Failure
DEBUG:hwilib.devices.trezorlib.transport.protocol:sending message: Initialize
DEBUG:hwilib.devices.trezorlib.transport.protocol:received message: Features
DEBUG:hwilib.devices.trezorlib.transport.protocol:sending message: GetFeatures
DEBUG:hwilib.devices.trezorlib.transport.protocol:received message: Features
DEBUG:hwilib.devices.trezorlib.transport.protocol:sending message: GetPublicKey
DEBUG:hwilib.devices.trezorlib.transport.protocol:received message: PassphraseRequest
DEBUG:hwilib.devices.trezorlib.transport.protocol:sending message: Cancel
DEBUG:hwilib.devices.trezorlib.transport.protocol:received message: Failure
DEBUG:hwilib.devices.trezorlib.transport.protocol:sending message: GetPublicKey
DEBUG:hwilib.devices.trezorlib.transport.protocol:received message: PassphraseRequest
DEBUG:hwilib.devices.trezorlib.transport.protocol:sending message: PassphraseAck
DEBUG:hwilib.devices.trezorlib.transport.protocol:received message: ButtonRequest
DEBUG:hwilib.devices.trezorlib.transport.protocol:sending message: ButtonAck
Please confirm action on your Trezor device
DEBUG:hwilib.devices.trezorlib.transport.protocol:received message: PublicKey
=> b'e0c4000000'

**Comment by gsud247** [comment]
GGGGs-iMac:osx64 ghh$ ./hwi -t trezor getxpub
usage: hwi getxpub [-h] path
{"error": "hwi getxpub: error: the following arguments are required: path", "code": -2}

**Comment by achow101** [comment]
Try `./hwi -t trezor --debug getxpub m/0h`

**Comment by gsud247** [comment]
Please confirm action on your Trezor device
2020-06-08 18:40:37 INFO	WasabiSynchronizer (258)	Downloaded filter for block 633777.
2020-06-08 18:41:20 ERROR	ConnectHardwareWalletViewModel (140)	System.Threading.Tasks.TaskCanceledException: A task was canceled.

same result

**Comment by molnard** [comment]
@gsud247 this information is very useful. For now, do not use Wasabi as it is adding another layer of complexity. Just run the HWI command from the command line. 

`./hwi -t trezor --debug getxpub m/0h`

Do not post the actual value of XPUB, replace it with gibberish.

**Comment by gsud247** [comment]
that worked

xpub showed up

i ran wasabi... searvhed for hardware wallet.. entered passphrase and it showed up in the gui

i loaded and im in.... thank you so very much

**Comment by gsud247** [comment]
i tried to git pull to update then wasabi like i would normally and i am not able to
can you help me get back to where i was before working with this branch so i can update and run the app from source like before?

**Comment by gsud247** [comment]
also... is this normal?.. when i was loading the new wallet i saw alot of yellow in the terminal.. i have tried to point wasabi to my MyNode full bitcoin node  (.onion adress).. (although im not sure if i succeeded) ... im not sure if that has anything to do with this message

it goes on like this for a minute or two before the wallet loads up

2020-06-09 18:52:59 INFO	P2pBlockProvider (290)	Disconnected node: fd87:d87e:eb43:8a87:580a:332d:7d89:f1d8. Block downloaded: 000000000000000000266f74c234babb2bef7fedece199b0f6553cc4bc9d7391.
2020-06-09 18:53:04 INFO	P2pBlockProvider (180)	TCP Connection succeeded, handshaking...
2020-06-09 18:53:13 WARNING	P2pBlockProvider (200)	Wasabi could not complete the handshake with the local node. Probably Wasabi is not whitelisted by the node.
Use "whitebind" in the node configuration. (Typically whitebind=127.0.0.1:8333 if Wasabi and the node are on the same machine and whitelist=1.2.3.4 if they are not.)
2020-06-09 18:53:13 WARNING	P2pBlockProvider (234)	System.OperationCanceledException: The operation was canceled.
   at System.Collections.Concurrent.BlockingCollection`1.TryTakeWithNoTimeValidation(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource)
   at System.Collections.Concurrent.BlockingCollection`1.TryTake(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Collections.Concurrent.BlockingCollection`1.Take(CancellationToken cancellationToken)
   at NBitcoin.Protocol.PollMessageListener`1.ReceiveMessage(CancellationToken cancellationToken)
   at NBitcoin.Protocol.NodeListener.ReceivePayload[TPayload](CancellationToken cancellationToken)
   at NBitcoin.Protocol.Node.VersionHandshake(NodeRequirement requirements, CancellationToken cancellationToken)
   at WalletWasabi.Wallets.P2pBlockProvider.TryDownloadBlockFromLocalNodeAsync(uint256 hash, CancellationToken cancellationToken) in /Users/gerasimosskaliotis/WalletWasabi/WalletWasabi/Wallets/P2pBlockProvider.cs:line 181
2020-06-09 18:53:34 INFO	P2pBlockProvider (290)	Disconnected node: fd87:d87e:eb43:c906:8b41:ec8d:382f:4ac7. Block downloaded: 00000000000000000003c98ef584cf56d7e211f0eda88a573df1bd79901b5f0a.
2020-06-09 18:53:35 INFO	P2pBlockProvider (180)	TCP Connection succeeded, handshaking...
2020-06-09 18:53:45 WARNING	P2pBlockProvider (200)	Wasabi could not complete the handshake with the local node. Probably Wasabi is not whitelisted by the node.
Use "whitebind" in the node configuration. (Typically whitebind=127.0.0.1:8333 if Wasabi and the node are on the same machine and whitelist=1.2.3.4 if they are not.)
2020-06-09 18:53:45 WARNING	P2pBlockProvider (234)	System.OperationCanceledException: The operation was canceled.
   at System.Collections.Concurrent.BlockingCollection`1.TryTakeWithNoTimeValidation(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource)
   at System.Collections.Concurrent.BlockingCollection`1.TryTake(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Collections.Concurrent.BlockingCollection`1.Take(CancellationToken cancellationToken)

**Comment by gsud247** [comment]
nevermind that second concern..

i believe i just solved this by entering my correct local bitcoin adress and port (.onion)

**Comment by molnard** [comment]
Very good. I am still not sure what happened. Wasabi is using HWI in the exact same way. So something was changed in your Trezor as a result of that command? 
Now your Trezor is started to work again with Wasabi? Even after restart?

**Comment by gsud247** [comment]
./hwi -t trezor --debug getxpub m/0h

The first time i ran this command I got this-

Please confirm action on your Trezor device
2020-06-08 18:40:37 INFO WasabiSynchronizer (258) Downloaded filter for block 633777.
2020-06-08 18:41:20 ERROR ConnectHardwareWalletViewModel (140) System.Threading.Tasks.TaskCanceledException: A task was canceled.

The second time i ran this command-

./hwi -t trezor --debug getxpub m/0h

It gave me my xpub

So i decided to restart and search for hardware wallet again.

And it worked

Does that make sense?

**Comment by molnard** [comment]
For me, it doesn't but as HWI is stateless (does not store any state, so it behaves the same every time you start it) something else would have changed - your computer or Trezor. Whatever was the reason it is solved.

**Comment by gsud247** [comment]
Would a virus scan application interfere with wasabi wallet/trezor t in the way i described?

**Comment by molnard** [comment]
I could only guess. But AV can detach or stop the communication with USB. I am not sure.

Here is just one case, possibly not related - but the thing is real: 

https://smallbusiness.chron.com/can-viruses-corrupt-usb-ports-79766.html

**Comment by gsud247** [comment]
I did delete mcafee virus scan for mac while troubleshooting. But during that time electrum was working fine w trezor on the mac w/ mcafee installed. So maybe..

**Comment by molnard** [comment]
Electrum is using a different interface to communicate with Trezor. So that makes sense - however, it is not a proof just a theory.
