### ISSUE TITLE
The BitBox02 does not accept a passphrase from the host

### ISSUE THREAD

**Issue by gabridome** [bitcoin-core/HWI#395]
```
./hwi.py enumerate
Traceback (most recent call last):
  File "./hwi.py", line 7, in <module>
    main()
  File "/Users/gbd/proj/HWI/hwilib/cli.py", line 282, in main
    result = process_commands(sys.argv[1:])
  File "/Users/gbd/proj/HWI/hwilib/cli.py", line 249, in process_commands
    return args.func(args)
  File "/Users/gbd/proj/HWI/hwilib/cli.py", line 46, in enumerate_handler
    return enumerate(password=args.password)
  File "/Users/gbd/proj/HWI/hwilib/commands.py", line 50, in enumerate
    result.extend(imported_dev.enumerate(password))
  File "/Users/gbd/proj/HWI/hwilib/devices/bitbox02.py", line 145, in enumerate
    client = Bitbox02Client(path)
  File "/Users/gbd/proj/HWI/hwilib/devices/bitbox02.py", line 218, in __init__
    raise BadArgumentError(
hwilib.errors.BadArgumentError: The BitBox02 does not accept a passphrase from the host. Please enable the passphrase option and enter the passphrase on the device during unlock.
```

I have enabled a passphrase on the the device:
1. Opened the bitbox app
2. I disconnected 
3. reconnected
5. input the password of the device
6. visually confirmed the password
7. closed the bitbox app

```
./hwi.py enumerate
Traceback (most recent call last):
  File "./hwi.py", line 7, in <module>
    main()
  File "/Users/gbd/proj/HWI/hwilib/cli.py", line 282, in main
    result = process_commands(sys.argv[1:])
  File "/Users/gbd/proj/HWI/hwilib/cli.py", line 249, in process_commands
    return args.func(args)
  File "/Users/gbd/proj/HWI/hwilib/cli.py", line 46, in enumerate_handler
    return enumerate(password=args.password)
  File "/Users/gbd/proj/HWI/hwilib/commands.py", line 50, in enumerate
    result.extend(imported_dev.enumerate(password))
  File "/Users/gbd/proj/HWI/hwilib/devices/bitbox02.py", line 145, in enumerate
    client = Bitbox02Client(path)
  File "/Users/gbd/proj/HWI/hwilib/devices/bitbox02.py", line 218, in __init__
    raise BadArgumentError(
hwilib.errors.BadArgumentError: The BitBox02 does not accept a passphrase from the host. Please enable the passphrase option and enter the passphrase on the device during unlock.
```

**Comment by gabridome** [comment]
After some experiment I have seen that if I use the ver. 1.2.0 the bitbox02 works almost as expected.
If I set up the Master branch, then everything stop working.
I would close this issue assuming `master` as an unstable branch which is not requested to work with all the wallets and I will open a separate issue for the problem I have seen with version 1.2.0
