### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'enumerate'

### ISSUE THREAD

**Issue by haarts** [bitcoin-core/HWI#462]
I must be particularly dense this morning but I'm having an issue with running HWI. 
I followed the install instructions in the README but when I run the `./hwi.py enumerate` command I get: 

```
❯ ./hwi.py enumerate
Traceback (most recent call last):
  File "./hwi.py", line 7, in <module>
    main()
  File "/tmp/HWI/hwilib/cli.py", line 296, in main
    result = process_commands(sys.argv[1:])
  File "/tmp/HWI/hwilib/cli.py", line 260, in process_commands
    return args.func(args)
  File "/tmp/HWI/hwilib/cli.py", line 60, in enumerate_handler
    return enumerate(password=args.password)
  File "/tmp/HWI/hwilib/commands.py", line 74, in enumerate
    result.extend(imported_dev.enumerate(password)) # type: ignore
  File "/tmp/HWI/hwilib/devices/trezor.py", line 677, in enumerate
    devs = hid.HidTransport.enumerate()
  File "/tmp/HWI/hwilib/devices/trezorlib/transport/hid.py", line 135, in enumerate
    for dev in hid.enumerate(0, 0):
AttributeError: 'NoneType' object has no attribute 'enumerate'
```

It seems that `hid` is `None`. But I can't seem to resolve the issue. I've just cloned that latest master.  Release 1.2.1 works as expected.

**Comment by achow101** [comment]
How have you installed the dependencies?

**Comment by jjakob** [comment]
I have the same issue with the master branch.

```
# hwi --debug enumerate
INFO:hwilib.devices.trezorlib.transport.hid:HID transport is disabled: /usr/lib/python3.9/site-packages/hid.cpython-39-x86_64-linux-gnu.so: undefined symbol: hid_get_input_report
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.9/hwi", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/hwilib/_cli.py", line 304, in main
    result = process_commands(sys.argv[1:])
  File "/usr/lib/python3.9/site-packages/hwilib/_cli.py", line 270, in process_commands
    return args.func(args)
  File "/usr/lib/python3.9/site-packages/hwilib/_cli.py", line 63, in enumerate_handler
    return enumerate(password=args.password)
  File "/usr/lib/python3.9/site-packages/hwilib/commands.py", line 117, in enumerate
    result.extend(imported_dev.enumerate(password)) # type: ignore
  File "/usr/lib/python3.9/site-packages/hwilib/devices/trezor.py", line 823, in enumerate
    devs = hid.HidTransport.enumerate()
  File "/usr/lib/python3.9/site-packages/hwilib/devices/trezorlib/transport/hid.py", line 135, in enumerate
    for dev in hid.enumerate(0, 0):
AttributeError: 'NoneType' object has no attribute 'enumerate'
```

This is on Gentoo with dev-python/libusb1 2.0.1

**Comment by jjakob** [comment]
https://github.com/trezor/cython-hidapi/issues/90
https://github.com/liquidctl/liquidctl/issues/144
https://bugs.archlinux.org/task/67103?dev=25983

**Comment by prusnak** [comment]
@jjakob what is the version of python3-hidapi installed on your system?

**Comment by jjakob** [comment]
dev-python/hidapi 0.11.0.2 from the "guru" overlay. The only other available version is 0.10.1.
I forgot to mention, this issue is also present with the latest HWI release 2.0.2 (also from the "guru" overlay).

**Comment by prusnak** [comment]
@jjakob I would take this to package maintainers of hidapi in Arch Linux. It seems there is a clash between hidapi and python-hidapi. (My hunch is they update hidapi and dev-python/hidapi not in sync). Anyway, I don't think there is anything we can do here.

**Comment by jjakob** [comment]
Thank you for that hint, it was indeed because of dev-libs/hidapi 0.8.0 being installed. Updating to 0.11.0 (marked unstable) fixed the issue. I think the relevant Gentoo bug is https://bugs.gentoo.org/696482
