### ISSUE TITLE
Segmentation Fault - Ubuntu 20.10 - Trezor One

### ISSUE THREAD

**Issue by spinza** [bitcoin-core/HWI#476]
Running Ubuntu 20.10.

Downloaded the release hwi-1.2.1-linux-amd64.tar.gz.

I extract it and run `./hwi-qt` but get errors.

Lots of font errors starting with this:
```
Fontconfig warning: line 5: unknown element "its:rules"                                                                         
Fontconfig warning: line 6: unknown element "its:translateRule"                                                                 
Fontconfig error: line 6: invalid attribute 'translate'                                                                         
Fontconfig error: line 6: invalid attribute 'selector'                                                                          
Fontconfig error: line 7: invalid attribute 'xmlns:its'                                                                         
Fontconfig error: line 7: invalid attribute 'version'                                                                           
Fontconfig warning: line 9: unknown element "description"                                                                       
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 4: unknown element "its:rules"   
Fontconfig warning: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 5: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/conf.d/10-hinting-slight.conf", line 6: invalid attribute 'xmlns:its'
```

It goes on a bit and ends with this:
```
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 5: invalid attribute 'selector'                  
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'xmlns:its'         
Fontconfig error: "/etc/fonts/conf.d/90-synthetic.conf", line 6: invalid attribute 'version'          
Fontconfig error: Cannot load default config file                                                                               
Traceback (most recent call last):                                                                                              
  File "hwi-qt.py", line 5, in <module>                                                                                         
  File "hwilib/gui.py", line 484, in main                                                                                       
  File "hwilib/gui.py", line 475, in process_gui_commands                                                                       
  File "hwilib/gui.py", line 320, in refresh_clicked                                                                            
KeyError: 'model'                                                                                                               
[608015] Failed to execute script hwi-qt                                                                                        
Segmentation fault (core dumped)   
```

**Comment by prusnak** [comment]
It seems Ubuntu has shipped broken version of fontconfig before: https://askubuntu.com/questions/1098809/applications-load-slowly-on-ubuntu-18-10-seems-related-to-fontconfig

That said, I think the `KeyError` you see is unrelated to the fontconfig warnings/errors.

**Comment by spinza** [comment]
Yes I thought it might be unrelated too.

**Comment by achow101** [comment]
The Fontconfig errors are unrelated to the crash.

What device are you using? Can you try using [2.0.0-rc.2](https://github.com/bitcoin-core/HWI/releases/tag/2.0.0-rc.2)?

**Comment by spinza** [comment]
I launched `hwi-2.0.0-rc.2-linux-amd64.tar.gz` and I now get:

```
$ ./hwi-qt 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
```

**Comment by prusnak** [comment]
> but get an error when I try to sign a tx. Shall I do a different issue for that?

Yes please

**Comment by spinza** [comment]
> Yes please. The current one is not related to Trezor at all, it is related to GUI/Qt.

Will do and agree current error seems unrelated to device but I was answering the device question @achow101 asked:

>What device are you using?

**Comment by achow101** [comment]
With the device plugged in, what do you get if you do `./hwi enumerate`?

**Comment by spinza** [comment]
Here you go before setting password:

```
$./hwi enumerate
[{"type": "trezor", "path": "webusb:002:2", "model": "trezor_1", "needs_pin_sent": true, "needs_passphrase_sent": false, "error": "Could not open client or get fingerprint information: Trezor is locked. Unlock by using 'promptpin' and then 'sendpin'.", "code": -12}]
```
