### ISSUE TITLE
HWI issue, Error scaning, Trezor and Ledger not detected

### ISSUE THREAD

**Issue by Shadovv007** [bitcoin-core/HWI#529]
Hi, 
I installed Sparrow and cant get detected any of my HW wallets, which work in other apps and with the same cable in the same usb spot. I did reboot, I dont use any other USB device, reinstalled Sparrow...dont know what else to try?

I ran hwi enumerate and got this :

Traceback (most recent call last):
  File "hwi.py", line 7, in <module>
  File "hwilib\_cli.py", line 305, in main
  File "hwilib\_cli.py", line 269, in process_commands
  File "hwilib\_cli.py", line 62, in enumerate_handler
  File "hwilib\commands.py", line 113, in enumerate
  File "hwilib\devices\trezor.py", line 714, in enumerate
  File "hwilib\devices\trezorlib\transport\webusb.py", line 118, in enumerate
  File "usb1\__init__.py", line 2087, in wrapper
  File "usb1\__init__.py", line 2196, in getDeviceIterator
  File "usb1\__init__.py", line 127, in mayRaiseUSBError
  File "usb1\__init__.py", line 119, in raiseUSBError
usb1.USBErrorNoDevice: LIBUSB_ERROR_NO_DEVICE [-4]
[7628] Failed to execute script hwi

Thanks!

**Comment by prusnak** [comment]
Which OS is that? Windows?

**Comment by Shadovv007** [comment]
Sorry, forgot to mention.. yes, its on Win 10.
On the same pc with the same conditions (cable, usb..) the Trezor works with Trezor Suite app, also here https://suite.trezor.io/ and also in Electrum desktop app.
Thanks!

**Comment by achow101** [comment]
Can you try without either Trezor suite or Electrum open, or anything else that may try to talk to the Trezor? This kind of error often appears when multiple apps are trying to use the device at the same time.

**Comment by Shadovv007** [comment]
Neither Trezor Suite nor Electrum is open :/
